# Generated by Django 4.2.1 on 2023-06-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('url', models.CharField(max_length=500)),
                ('urlImage', models.CharField(max_length=500)),
            ],
        ),
    ]
