# Generated by Django 4.2.1 on 2023-06-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='sports', max_length=100),
            preserve_default=False,
        ),
    ]
